version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: sh docker/gunicorn.sh
    ports:
      - 10080:8080
    volumes:
      - .:/opt/:rw
      - data:/opt/data

volumes:
  data: {}