version: '3'

services:
  api:
    build:
      args:
        APP_ENV: 'local'
    networks:
      - util-net
    depends_on:
      - redis

  redis:
    image: redis:4-alpine
    volumes:
    - redis-data:/data
    networks:
    - util-net


networks:
  util-net:
    external: true

volumes:
  redis-data: {}