version: '3'

services:
  api:
    image: bielr/util-aligner-api
    restart: unless-stopped
    build:
      context: ./docker/
      dockerfile: ./Dockerfile_base
    command: sh docker/gunicorn.sh --timeout 720
    ports:
      - 10080:8080
    volumes:
      - .:/opt/:rw
      - data:/opt/data

volumes:
  data: {}
