version: '3'

services:
  api:
    build: .
    command: gunicorn api.server:app -c settings_gunicorn.py
    networks:
      - util-net
    ports:
      - 0.0.0.0:10080:8080
    volumes:
      - .:/opt/:rw
      - data:/opt/data

  redis:
    image: redis:4-alpine
    volumes:
    - redis-data:/data
    networks:
    - util-net

networks:
  util-net: {}

volumes:
  data: {}
  redis-data: {}